# Generated by Django 5.0.6 on 2024-06-09 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_alter_renter_emailrenter_alter_seller_emailseller'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appCountryName', models.CharField(max_length=50)),
                ('appRegionStateName', models.CharField(max_length=50)),
                ('appCityName', models.CharField(max_length=50)),
                ('appStreetName', models.CharField(max_length=50)),
                ('appHouseNumber', models.PositiveIntegerField(default=1)),
                ('appHouseCorpusNumber', models.PositiveIntegerField(default=None)),
                ('appHouseNumberOfFloors', models.PositiveIntegerField(default=1)),
                ('appFloorNumber', models.IntegerField(default=1)),
                ('appNumber', models.PositiveIntegerField(default=1)),
                ('appNumberOfSquare', models.PositiveIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(1000)])),
                ('appNumberOfRooms', models.PositiveIntegerField(default=1)),
                ('appNumberOfBedrooms', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10)])),
                ('appShortDiscription', models.CharField(max_length=100)),
                ('appMaxGuests', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(40)])),
            ],
        ),
        migrations.CreateModel(
            name='CityList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=50)),
                ('regionName', models.CharField(max_length=50)),
                ('cityName', models.CharField(max_length=50)),
                ('subway', models.BooleanField(default=False)),
                ('funicular', models.BooleanField(default=False)),
                ('monorail', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StreetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streetTypeName', models.CharField(max_length=50)),
                ('streetTypeNameRus', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
